# EXPLORE THE MESSENGER GAME

In [1]:
import messenger.envs.config as config

In [3]:
config.ALL_ENTITIES

[Entity(name='airplane', id=2),
 Entity(name='mage', id=3),
 Entity(name='dog', id=4),
 Entity(name='bird', id=5),
 Entity(name='fish', id=6),
 Entity(name='scientist', id=7),
 Entity(name='thief', id=8),
 Entity(name='ship', id=9),
 Entity(name='ball', id=10),
 Entity(name='robot', id=11),
 Entity(name='queen', id=12),
 Entity(name='sword', id=13),
 Entity(name='wall', id=14),
 Entity(name='no_message', id=15),
 Entity(name='with_message', id=16)]

In [105]:
def printObsView(obs):
    print(obs["entities"].sum(axis=-1)+obs["avatar"].sum(axis=-1))
    ids = np.delete(np.unique(obs["entities"]), 0)
    id_names = {str(int(i)): config.ALL_ENTITIES[int(i)-2].name for i in ids}
    id_names["15"] = "avatar_no_message"
    id_names["16"] = "avatar_with_message"
    for key, value in id_names.items():
        print(f"{key}: {value}")

In [4]:
import gym
env = gym.make('msgr-train-v2')

In [169]:
obs, manual = env.reset()

## INSTRUCTIONS

In [170]:
manual

['a restricted robber is the document that flees from you.',
 'the female monarch does not move, but is a dangerous opponent.',
 'the jet carrying a crucial target chases you.']

## DO STUFF

In [141]:
config.ACTIONS

Actions(up=0, down=1, left=2, right=3, stay=4)

In [164]:
obs, reward, done, info = env.step(2)
printObsView(obs)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  8.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
8: thief
15: avatar_no_message
16: avatar_with_message


## SHOW RESULTS

In [165]:
done

True

In [166]:
reward

1.0

In [144]:
printObsView(obs)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.  0.  0.  7.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
2: airplane
7: scientist
8: thief
15: avatar_no_message
16: avatar_with_message


## 